### ISSUE TITLE
Any plan to update for CLION 2023 ?

### ISSUE THREAD

**Issue by gd-harco** [yahyasemih/ft_header#1]
Hi ! 

Title is pretty much the whole issue, the plugin is currently not compatible with the 2023 version of Clion. Do you plan to update ? 

Thanks a lot for the plugin !

**Comment by yahyasemih** [comment]
Hello,

Thank you for reporting it, I will update it and it should be available one the changes approved by Jetbrains.

**Comment by gd-harco** [comment]
Awesome, everyone at 42Lyon thanks you !

**Comment by yahyasemih** [comment]
The update is available now, I also updated [ft_norminette](https://plugins.jetbrains.com/plugin/20723-ft-norminette) plugin to be compatible with CLion 2023.
