### ISSUE TITLE
Creation time is broken

### ISSUE THREAD

**Issue by Desoroxxx** [yahyasemih/ft_header#12]
![image](https://github.com/user-attachments/assets/0358108f-a8fd-423c-acae-5ffa58b02fca)

The image speaks for itself, this always happen

**Comment by yahyasemih** [comment]
Creation time is provided by the IDE virtual file system, any incorrect time is out of the plugin's control. Does it happen if you create the header on a new created file or already existing one?

**Comment by Desoroxxx** [comment]
> Creation time is provided by the IDE virtual file system, any incorrect time is out of the plugin's control. Does it happen if you create the header on a new created file or already existing one?

I create a new file, save it, and this happens, on Ubuntu and CLion 2024.2.2.

**Comment by Desoroxxx** [comment]
Fixed by CLion 2024.3
