### ISSUE TITLE
Long Email being stripped

### ISSUE THREAD

**Issue by BrunoCostaGH** [yahyasemih/ft_header#2]
When the email is too long header cuts out the email instead of removing white space. try with {user}@student.42porto.com

**Comment by yahyasemih** [comment]
It was intended to do so as it's the same behavior in the 42 Vim command for headers.

**Comment by BrunoCostaGH** [comment]
Oh. It's just a pain to fix it up all the time. Vim Header set us up with marvin@42.fr. Since I changed to VSCode I set my email to my actual email and it worked perfectly, was just expected the same behavior, as the VSCode extension, when switching to CLion.

**Comment by yahyasemih** [comment]
The Vim Header can also set your email if you set `MAIL` env variables. Anyway, I will change this behavior.

**Comment by yahyasemih** [comment]
I applied a fix. The update should be available tomorrow on the Marketplace.
