### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by thule-re** [yahyasemih/ft_header#4]
When I try to install the newest version of the plugin I get the following message:
> Plugin 'Ft_header' (version '1.6') is not compatible with the current version of the IDE, because it requires build 222.* or newer but the current build is CL-222.4167.35

**Comment by yahyasemih** [comment]
Try to install the latest version of CLion (2023.1.1).

**Comment by thule-re** [comment]
Yep that fixed it. Thanks a lot
