### ISSUE TITLE
Extension not creating header in file

### ISSUE THREAD

**Issue by gd-harco** [yahyasemih/ft_header#6]
Hi ! 
for some time, this plugin hasn't been working in my Clion install, whether it is on my personal computer or on the one at 42.

The extension is correctly configure in the tools settings of CLion.

Clion version : 2023.1.4
Ft_header version : 1.7
OS : Ubuntu 22.04.1 LTS

My co-learner at 42 doesn't have this issue, I'm the only one known to have it.
Any idea ? Do you want some log or anything ?

**Comment by BrunoCostaGH** [comment]
In which file extensions are you trying to create the header?

**Comment by gd-harco** [comment]
> In which file extensions are you trying to create the header?

.C and .H 
Saving either one doesn't produce any result

**Comment by BrunoCostaGH** [comment]
what is the specified regex in settings?

**Comment by gd-harco** [comment]
> what is the specified regex in settings?

`^.+\.[ch]$`
I thought maybe there was a conflict with another extension, but having it as the only one (from the marketplace) enabled doesn't fox it.

**Comment by BrunoCostaGH** [comment]
That seems to be alright, what steps are you using to add the header to the file?

**Comment by yahyasemih** [comment]
Hello, I did not test the extension other than MacOs, normally it should work on Linux as well. I will take a look asap.
If you have any errors or logs that can help i will be grateful

**Comment by gd-harco** [comment]
I can confirm it does work on Linux, at least on my co-learner installation.
Do you have indication on how to generate logs for your extension ?

**Comment by yahyasemih** [comment]
just to check, what are you using as email and login in the settings? if empty what are your `USER`, `LOGNAME`, `EMAIL` and `MAIL` env variables?

**Comment by gd-harco** [comment]
Here are the settings in the TOOLS menu :
![image](https://github.com/yahyasemih/ft_header/assets/93791134/faca8b2a-7c11-46ed-a1ab-0556b70e227c)
MAIL and EMAIL are empty.
As this is the first week of august Pool, I don't have access on my campus account, but it doesn't work on my own computer as well.

**Comment by yahyasemih** [comment]
Not sure where the logs are on Linux, but it should be an `idea.log` file under `CLion.XX` folder depending on your current version.

**Comment by gd-harco** [comment]
I'll do, and I'll close the issue if the update fixed the issue. Otherwise, I'll publish the log file of a new project. Thanks a lot for your help !

**Comment by yahyasemih** [comment]
The update is available to download, could you please check?

**Comment by gd-harco** [comment]
Just did ! Launched the IDE once to update the header. 
Then I created a new project. Loaded the makefile, created my main.c, saved it both automatically and manually but no header to be found. 
Please find the log for this specific session attach to this message.
[truncated_idea.log](https://github.com/yahyasemih/ft_header/files/12289203/truncated_idea.log)

**Comment by yahyasemih** [comment]
From the logs it seems that the plugin was not triggered when you save the files, can you install this jar manually? (plugins -> install from disk)
[ft_header-1.8.jar.zip](https://github.com/yahyasemih/ft_header/files/12289456/ft_header-1.8.jar.zip)
and send me the logs again
Thanks in advance!

**Comment by gd-harco** [comment]
Seems like the manual installation fixed the issue. The plugin isn't triggered by autosave, but that might be the intended behavior.
Do you still want to see the logs ?

**Comment by yahyasemih** [comment]
Yes please. For triggering it's intended to be by manual saving, otherwise the file is not properly synchronized by the IDE most of the time.

**Comment by gd-harco** [comment]
Sorry for the delay ! Here is the log. After reading through it, I might be very dumb, and the file wasn't updating because I was using a wrong keymap for manual saving...
[Log_manual_install.log](https://github.com/yahyasemih/ft_header/files/12295399/Log_manual_install.log)

**Comment by yahyasemih** [comment]
Now it looks good, I will close the issue.
